.TH peertube-cli 1 2021-11-07 KILL-9

.SH NAME
peertube-cli \- A peertube CLI client.
.SH SYPNOSIS
.B peertube-cli
[\-\-instance=INSTANCE] [\-\-resolution=[0|1|...|n]] [\-\-player=PLAYER] [URL] 
.SH DESCRIPTION
peertube-cli is a peertube client. If no parameters are given, it will
use the config file
.B
~/.ptclirc
or anything in the
.B
PTCLIRC
env
.SH CONFIG
The file
.B
~/.ptclirc
is written in perl using perl's hashes. And it contains 3
values, instance, resolution and player. peertube-cli will use the
values set in this file if nothing is passed with getopt arguments.
